services:
  talento-ai-agent:
    container_name: talento-ai-agent
    build:
      context: .
      dockerfile: Dockerfile
    image: talento-ai-agent:1.0.4
    ports:
      - "2024:2024"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - talento-network
networks:
  talento-network:
    driver: bridge
