version: '3.8'

services:
  talento-ai-agent:
    image: talento-ai-agent:1.0.4
    container_name: talento-ai-agent
    ports:
      - "2024:2024"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - talento-network

networks:
  talento-network:
    driver: bridge
